### ISSUE TITLE
Custom links in Zappbar buttons and menu

### ISSUE THREAD

**Issue by jzfriday** [kmhcreative/zappbar#11]
Hello there, well i have this website with a subdomain and the Zappbar plugin installed on both of them, what i need is the Zappbar buttons link to my main site pages. _Forget about the menu i only need to create another menu with my custom links and checkmark the "Zappbar menu left/right" option._

I'm a completly noob with php so i can't figure out how to do this by myself, there is an easy way i can add a "custom link" in my plugin?

**Comment by kmhcreative** [comment]
Zappbar only supports custom links as menu items.  If I'm understanding correctly, wiring a button to "Go to Home Page" in your sub-domain site is going to the sub-domain site's homepage but you want it to go to the parent domain's homepage?  The only way I can think of to do that is create a custom page in your sub-domain you can wire the Zappbar button to and then set up a redirect from that page to the parent domain's homepage.  It's a little clumsy but it'll get you there.
