### ISSUE TITLE
Can't access settings?

### ISSUE THREAD

**Issue by klayfoam** [kmhcreative/zappbar#12]
Hey, just activated the plugin-- every time I try to access the settings, I get a page that tells me "sorry, you are not allowed to access this page". Is this a bug of some sort, or something I'm doing wrong?

**Comment by kmhcreative** [comment]
There can be a number of reasons why you'd encounter that error.  If this was a fresh install of ZappBar, not an update, you'd have to have FTP'd it to your site so the first thing I'd check is the file permissions.  But like I said there are lots of reasons, here's a good article on resolving them:
[https://www.hostinger.com/tutorials/fix-sorry-you-are-not-allowed-to-access-this-page-wordpress](https://www.hostinger.com/tutorials/fix-sorry-you-are-not-allowed-to-access-this-page-wordpress).

I can tell you that I'm using ZappBar 0.2.5 on my own sites running WordPress 5.2.5 to 5.3.2 without any issues.  I haven't been testing it on anything older than 5.0.3 so if you're still running an even older version of WordPress you may have to stick with an earlier ZappBar release.
