### ISSUE TITLE
Notice Errors

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#4]
Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()
instead. in /home/frumph/public_html/dev/wp-includes/functions.php on line 3457

Notice: Undefined index: button_bg_hover_opacity in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 43

Notice: Undefined index: header in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 283

Notice: Undefined variable: hide_header in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 810

Notice: Undefined variable: hide_header in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 848

Notice: Undefined variable: hide_header in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 863

**Comment by Frumph** [comment]
Notice: Undefined offset: 0 in /home/frumph/public_html/dev/wp-content/plugins/zappbar/functions/utility_functions.php on line 50

**Comment by kmhcreative** [comment]
At some point for some reason I apparently turned WP debugging off on my dev server. DOH!  Ok, I'm not seeing any more of these notices on my dev server on three different WP installations with different themes, so I think I squashed them all.
