### ISSUE TITLE
add github updater code to main file

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#5]
Referencing plugin: https://github.com/afragen/github-updater

info to add to the top of your readme.txt file for the plugin

GitHub Plugin URI: https://github.com/kmhcreative/zappbar
GitHub Branch: master

This will let users like me use the github updater plugin to auto-update when you create 'releases' in github.

**Comment by kmhcreative** [comment]
Wow, I didn't know such a thing existed.  I skimmed the reference and I only saw mention of putting that code in the plugin header, so I'm confused - do I also need it in a "readme.txt" file too?

**Comment by Frumph** [comment]
naw my bad, meant the main php file for the plugin where the ver. # is

**Comment by kmhcreative** [comment]
Ok, just pushed that and a couple other minor changes.  Haven't declared it a new "release" yet tho.

**Comment by Frumph** [comment]
That's fine, when you do you can checkmark it pre-release and such and it will compile the current into a .zip and the updater plugin will make it so that it shows in the dashboard as being needing updated like a regular plugin does and even update it from the github instead of the wordpress.org repo, for a theme its perfect cause themes take forever to get updated on the repo

**Comment by Frumph** [comment]
wish i had ya on facebook messenger, could tell you about the CP 4.3 changes ;/
