### ISSUE TITLE
notice

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#7]
Notice: Undefined index: button_bg_hover_opacity in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/dynamic-css.php on line 41

stays even after clicking save again ;/

**Comment by kmhcreative** [comment]
Oops, the "button_bg_hover_opacity" var name was wrong in the defaults set during activation.  Though I couldn't seem to reproduce this notice I'm also not sure why saving settings doesn't make it go away.

**Comment by Frumph** [comment]
Undefined index: social_panel in /home/frumph/public_html/dev/wp-content/plugins/zappbar/includes/html_inject.php on line 333
