### ISSUE TITLE
Comic post under comic on comicpress

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#8]
http://dev.frumph.net/  If you look here (and it's active, will be for awhile) the comic blog post section gets a little ..off.    Noticed it yesterday as well

**Comment by Frumph** [comment]
going over the retrofit.css and the other one and there's a lot of things that could be changed/even removed the articles already resize and shouldn't use floats which is why it's happening

the other one is the display: none; on the 'archive clutter' thing, is affecting the home page as well is why the comic-post box is having issues, cleaned it up on my site for testing currently, still can't find where the total site width is being forced to 980 yet ;/

**Comment by kmhcreative** [comment]
Yeah, I just pushed an update which now limits those to the archive page.  I had no idea the "comic post" used the same classes.  Keep in mind this isn't just for ComicPress 4.x.  It's also for ComicPress 2.9 and, really, ANY WordPress theme, so there may be what looks like a lot of redundant stuff in it, but it's necessary to make it work with _other_ themes (including some other comic themes like MangaPress and Webcomic)

**Comment by Frumph** [comment]
_nod_ totally understood.   I have learned from your coding how to add things to the comicpress 4.3 theme and it's now responsive on it's own up to a point
